var userAge = +prompt('Введите Свой Возраст')
var answer = ''
switch(userAge){
    case 1 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 2 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 3 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 4 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 5 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 6 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 7 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 8 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 9 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 10 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 11 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 12 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 13 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 14 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 15 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 16 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 17 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 18 : answer = 'Вы еще молоды. Вам нужно учится';break
    case 19 : answer = 'Вам нужно работать';break
    case 20 : answer = 'Вам нужно работать';break
    case 21 : answer = 'Вам нужно работать';break
    case 22 : answer = 'Вам нужно работать';break
    case 23 : answer = 'Вам нужно работать';break
    case 24 : answer = 'Вам нужно работать';break
    case 25 : answer = 'Вам нужно работать';break
    case 26 : answer = 'Вам нужно работать';break
    case 27 : answer = 'Вам нужно работать';break
    case 28 : answer = 'Вам нужно работать';break
    case 29 : answer = 'Вам нужно работать';break
    case 30 : answer = 'Вам нужно работать';break
    case 31 : answer = 'Вам нужно работать';break
    case 32 : answer = 'Вам нужно работать';break
    case 33 : answer = 'Вам нужно работать';break
    case 34 : answer = 'Вам нужно работать';break
    case 35 : answer = 'Вам нужно работать';break
    case 36 : answer = 'Вам нужно работать';break
    case 37 : answer = 'Вам нужно работать';break
    case 38 : answer = 'Вам нужно работать';break
    case 39 : answer = 'Вам нужно работать';break
    case 40 : answer = 'Вам нужно работать';break
    case 41 : answer = 'Вам нужно работать';break
    case 42 : answer = 'Вам нужно работать';break
    case 43 : answer = 'Вам нужно работать';break
    case 44 : answer = 'Вам нужно работать';break
    case 45 : answer = 'Вам нужно работать';break
    case 46 : answer = 'Вам нужно работать';break
    case 47 : answer = 'Вам нужно работать';break
    case 48 : answer = 'Вам нужно работать';break
    case 49 : answer = 'Вам нужно работать';break
    case 50 : answer = 'Вам нужно работать';break
    case 51 : answer = 'Вам скоро на пенсию';break
    case 52 : answer = 'Вам скоро на пенсию';break
    case 53 : answer = 'Вам скоро на пенсию';break
    case 54 : answer = 'Вам скоро на пенсию';break
    case 55 : answer = 'Вам скоро на пенсию';break
    case 56 : answer = 'Вам скоро на пенсию';break
    case 57 : answer = 'Вам скоро на пенсию';break
    case 58 : answer = 'Вам скоро на пенсию';break
    case 59 : answer = 'Вам скоро на пенсию';break
    case 60 : answer = 'Вы пенсионер';break
    case 61 : answer = 'Вы пенсионер';break
    case 62 : answer = 'Вы пенсионер';break
    case 63 : answer = 'Вы пенсионер';break
    case 64 : answer = 'Вы пенсионер';break
    case 65 : answer = 'Вы пенсионер';break
    case 66 : answer = 'Вы пенсионер';break
    case 67 : answer = 'Вы пенсионер';break
    case 68 : answer = 'Вы пенсионер';break
    case 69 : answer = 'Вы пенсионер';break
    case 70 : answer = 'Вы пенсионер';break
    case 71 : answer = 'Вы пенсионер';break
    case 72 : answer = 'Вы пенсионер';break
    case 73 : answer = 'Вы пенсионер';break
    case 74 : answer = 'Вы пенсионер';break
    case 75 : answer = 'Вы пенсионер';break
    case 76 : answer = 'Вы пенсионер';break
    case 77 : answer = 'Вы пенсионер';break
    case 78 : answer = 'Вы пенсионер';break
    case 79 : answer = 'Вы пенсионер';break
    case 80 : answer = 'Вы пенсионер';break
    case 81 : answer = 'Вы пенсионер';break
    case 82 : answer = 'Вы пенсионер';break
    case 83 : answer = 'Вы пенсионер';break
    case 84 : answer = 'Вы пенсионер';break
    case 85 : answer = 'Вы пенсионер';break
    case 86 : answer = 'Вы пенсионер';break
    case 87 : answer = 'Вы пенсионер';break
    case 88 : answer = 'Вы пенсионер';break
    case 89 : answer = 'Вы пенсионер';break
    case 90 : answer = 'Вы пенсионер';break
    case 91 : answer = 'Вы пенсионер';break
    case 92 : answer = 'Вы пенсионер';break
    case 93 : answer = 'Вы пенсионер';break
    case 94 : answer = 'Вы пенсионер';break
    case 95 : answer = 'Вы пенсионер';break
    case 96 : answer = 'Вы пенсионер';break
    case 97 : answer = 'Вы пенсионер';break
    case 98 : answer = 'Вы пенсионер';break
    case 99 : answer = 'Вы пенсионер';break
    case 100 : answer = 'Вы пенсионер';break
    case 101 : answer = 'Вы пенсионер';break
    case 102 : answer = 'Вы пенсионер';break
    case 103 : answer = 'Вы пенсионер';break
    case 104 : answer = 'Вы пенсионер';break
    case 105 : answer = 'Вы пенсионер';break
    case 106 : answer = 'Вы пенсионер';break
    case 107 : answer = 'Вы пенсионер';break
    case 108 : answer = 'Вы пенсионер';break
    case 109 : answer = 'Вы пенсионер';break
    case 110 : answer = 'Вы пенсионер';break
    case 111 : answer = 'Вы пенсионер';break
    case 112 : answer = 'Вы пенсионер';break
    case 113 : answer = 'Вы пенсионер';break
    case 114 : answer = 'Вы пенсионер';break
    case 115 : answer = 'Вы пенсионер';break
    case 116 : answer = 'Вы пенсионер';break
    case 117 : answer = 'Вы пенсионер';break
    case 118 : answer = 'Вы пенсионер';break
    case 119 : answer = 'Вы пенсионер';break
    case 120 : answer = 'Вы пенсионер';break
    case 121 : answer = 'Вы пенсионер';break
    case 122 : answer = 'Вы пенсионер';break
    case 123 : answer = 'Вы пенсионер';break
    case 124 : answer = 'Вы пенсионер';break
    case 125 : answer = 'Вы пенсионер';break
    case 126 : answer = 'Вы пенсионер';break
    case 127 : answer = 'Вы пенсионер';break
    case 128 : answer = 'Вы пенсионер';break
    case 129 : answer = 'Вы пенсионер';break
    case 130 : answer = 'Вы пенсионер';break
    case 131 : answer = 'Вы пенсионер';break
    case 132 : answer = 'Вы пенсионер';break
    case 133 : answer = 'Вы пенсионер';break
    case 134 : answer = 'Вы пенсионер';break
    case 135 : answer = 'Вы пенсионер';break
    case 136 : answer = 'Вы пенсионер';break
    case 137 : answer = 'Вы пенсионер';break
    case 138 : answer = 'Вы пенсионер';break
    case 139 : answer = 'Вы пенсионер';break
    case 140 : answer = 'Вы пенсионер';break
    case 141 : answer = 'Вы пенсионер';break
    case 142 : answer = 'Вы пенсионер';break
    case 143 : answer = 'Вы пенсионер';break
    case 144 : answer = 'Вы пенсионер';break
    case 145 : answer = 'Вы пенсионер';break
    case 146 : answer = 'Вы пенсионер';break
    case 147 : answer = 'Вы пенсионер';break
    case 148 : answer = 'Вы пенсионер';break
    case 149 : answer = 'Вы пенсионер';break
    case 150 : answer = 'Вы пенсионер';break
    default: answer = 'Что-то пошло не так'
}
alert(answer)

a=parseInt(prompt("Введите число:")); 
b=parseInt(prompt("Введите число:")); 
c=parseInt(prompt("Введите число:"));  
if((b<a && a<c) || (c<a && a<b)) alert(a);
if((a<b && b<c) || (c<b && b<a)) alert(b);
if((a<c && c<b) || (b<c && c<a)) alert(c);


var userTime = +prompt('Введите Время')
var answer = ''
switch(userTime){
    case 1 : answer = '1 Час Ночи';break
    case 2 : answer = '2 Часа Ночи';break
    case 3 : answer = '3 Часа Ночи';break
    case 4 : answer = '4 Часа Ночи';break
    case 5 : answer = '5 Часов Ночи';break
    case 6 : answer = '6 Часов Утра';break
    case 7 : answer = '7 Часов Утра';break
    case 8 : answer = '8 Часов Утра';break
    case 9 : answer = '9 Часов Утра';break
    case 10 : answer = '10 Часов Утра';break
    case 11 : answer = '11 Часов Утра';break
    case 12 : answer = '12 Часов Дня';break
    case 13 : answer = '1 Час Дня';break
    case 14 : answer = '2 Часа Дня';break
    case 15 : answer = '3 Часа Дня';break
    case 16 : answer = '4 Часа Дня';break
    case 17 : answer = '5 Часов Дня';break
    case 18 : answer = '6 Часов Вечера';break
    case 19 : answer = '7 Часов Вечера';break
    case 20 : answer = '8 Часов Вечера';break
    case 21 : answer = '9 Часов Вечера';break
    case 22 : answer = '10 Часов Вечера';break
    case 23 : answer = '11 Часов Вечера';break
    case 24 : answer = '12 Часов Ночи';break
    default: answer = 'Что-то пошло не так'
}
alert(answer)